<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/DBSCAN_x_Hierarquico_x_KMeans_Machine_Learning_e_Data_Science_com_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DBSCAN

## Base Salario x Idade

In [1]:
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [2]:
x = [20, 27, 21, 37, 46, 53,55,47,52,32,39,41,39,48,48]
y = [1000, 1200, 2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

In [3]:
base_salario = np.array([[20,1000], [27, 1200], [21, 2900], [37, 1850], [46, 900], [53, 950], [55, 2000], [47, 2100], [52, 3000], [32, 5900], [39, 4100], [41, 5100], [39, 7000], [48, 5000], [48, 6500]])
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [4]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [5]:
from sklearn.cluster import DBSCAN

In [8]:
dbscan_salario = DBSCAN(eps=0.95, min_samples=2)
dbscan_salario.fit(base_salario)

DBSCAN(eps=0.95, min_samples=2)

In [9]:
rotulos = dbscan_salario.labels_
rotulos

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

In [10]:
graficos = px.scatter(x=x, y=y, color=rotulos)
graficos.show()

## Base cartão de crédito

In [11]:
base_cartao = pd.read_csv('credit_card_clients.csv', header=1)
base_cartao

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [12]:
base_cartao['BILL_TOT'] = base_cartao['BILL_AMT1'] + base_cartao['BILL_AMT2'] + base_cartao['BILL_AMT3'] + base_cartao['BILL_AMT4'] + base_cartao['BILL_AMT5']

In [13]:
X_cartao = base_cartao.iloc[:,[1,25]].values
X_cartao

array([[ 20000,   7704],
       [120000,  13816],
       [ 90000,  86104],
       ...,
       [ 30000,  51139],
       [ 80000, 217667],
       [ 50000, 215561]])

In [21]:
scaler_cartao = StandardScaler()
X_cartao = scaler_cartao.fit_transform(X_cartao)
X_cartao

array([[-1.13672015, -0.68703183],
       [-0.3659805 , -0.66822573],
       [-0.59720239, -0.44580167],
       ...,
       [-1.05964618, -0.55338602],
       [-0.67427636, -0.04099347],
       [-0.90549825, -0.04747345]])

In [26]:
dbscan_cartao = DBSCAN(eps=0.37, min_samples=5)
rotulos = dbscan_cartao.fit_predict(X_cartao)
rotulos

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
np.unique(rotulos, return_counts=True)

(array([-1,  0,  1,  2]), array([   48, 29934,    14,     4]))

In [28]:
graficos = px.scatter(x=X_cartao[:,0], y=X_cartao[:,1], color=rotulos)
graficos.show()

## DBSCAN x Hierárquico x K-means

In [29]:
from sklearn import datasets

In [32]:
X_random, y_random = datasets.make_moons(n_samples=1500, noise=0.09)

In [33]:
grafico = px.scatter(x=X_random[:,0], y=X_random[:,1])
grafico.show()

## KMEANS

In [35]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2)
kmeans.fit(X_random)

KMeans(n_clusters=2)

In [36]:
grafico = px.scatter(x=X_random[:,0], y=X_random[:,1], color=kmeans.labels_)
grafico.show()

## HIERARQUICO

In [38]:
from sklearn.cluster import AgglomerativeClustering

hc = AgglomerativeClustering(n_clusters=2, metric='euclidean', linkage='ward')
rotulos = hc.fit_predict(X_random)
grafico = px.scatter(x=X_random[:,0], y=X_random[:,1], color=rotulos)
grafico.show()

## DBSCAN

In [43]:
dbscan = DBSCAN(eps=0.1)
rotulos = dbscan.fit_predict(X_random)
grafico = px.scatter(x=X_random[:,0], y=X_random[:,1], color=rotulos)
grafico.show()