<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/KMeans_Mais_Atributos_Machine_Learning_e_Data_Science_com_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-means - Agrupamento

In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 57.9 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [2]:
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [3]:
x = [20, 27, 21, 37, 46, 53,55,47,52,32,39,41,39,48,48]
y = [1000, 1200, 2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

In [4]:
grafico =px.scatter(x=x, y=y, title='Agrupamento de Clientes')
grafico.show()

In [5]:
matriz = []
for i in range(len(x)):
  matriz.append([x[i], y[i]])
matriz

[[20, 1000],
 [27, 1200],
 [21, 2900],
 [37, 1850],
 [46, 900],
 [53, 950],
 [55, 2000],
 [47, 2100],
 [52, 3000],
 [32, 5900],
 [39, 4100],
 [41, 5100],
 [39, 7000],
 [48, 5000],
 [48, 6500]]

In [6]:
base_salario = np.array([[20,1000], [27, 1200], [21, 2900], [37, 1850], [46, 900], [53, 950], [55, 2000], [47, 2100], [52, 3000], [32, 5900], [39, 4100], [41, 5100], [39, 7000], [48, 5000], [48, 6500]])
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [7]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [8]:
matriz = scaler_salario.fit_transform(matriz)
matriz

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [9]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [10]:
c = kmeans_salario.cluster_centers_
c

array([[-1.63312883, -0.77505093],
       [ 0.07703438,  1.11413572],
       [ 0.73953003, -0.72661025]])

In [11]:
scaler_salario.inverse_transform(c)

array([[  22.66666667, 1700.        ],
       [  41.16666667, 5600.        ],
       [  48.33333333, 1800.        ]])

In [12]:
r = kmeans_salario.labels_

In [13]:
r

array([0, 0, 0, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int32)

In [14]:
grafico1 = px.scatter(x=base_salario[:,0], y=base_salario[:,1], color=r)
grafico2 = px.scatter(x=c[:,0], y=c[:,1], size=[12, 12, 12])
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3.show()

# Dados Randômicos

In [15]:
from sklearn.datasets import make_blobs

In [16]:
X_random, y_random = make_blobs(n_samples=200, centers=5, random_state=0)

In [17]:
X_random

array([[ 1.36069966,  0.74802912],
       [-3.27894024,  9.89995288],
       [ 0.58894326,  4.00148458],
       [-0.97373942,  6.94454493],
       [ 2.43169305, -0.20173713],
       [ 0.62835793,  4.4601363 ],
       [-2.16434104,  2.52061045],
       [-0.65392827,  4.76656958],
       [ 0.73240494,  2.87562511],
       [ 1.956815  ,  0.23418537],
       [ 2.11567076,  3.06896151],
       [ 3.18190344, -0.18226785],
       [ 7.01769098, -3.35367647],
       [-2.34026827,  1.45145793],
       [ 0.30380963,  3.94423417],
       [ 0.829832  ,  1.74202664],
       [-3.06770103,  2.98114426],
       [-1.36641982,  7.15528181],
       [-1.10630261,  7.5161316 ],
       [ 2.41163392,  1.60423683],
       [-2.37508158,  7.10478226],
       [-2.47135027,  2.50783257],
       [ 2.47034915,  4.09862906],
       [-1.63313558,  7.9298116 ],
       [ 8.58924431, -0.67161883],
       [ 3.92282648,  1.80370832],
       [-1.38420548,  8.97235138],
       [ 1.05566092,  6.77544419],
       [ 9.08260172,

In [18]:
y_random

array([1, 3, 0, 3, 1, 0, 2, 0, 2, 1, 0, 1, 4, 2, 0, 1, 2, 3, 3, 1, 3, 2,
       0, 3, 4, 1, 3, 3, 4, 3, 1, 2, 0, 0, 2, 0, 4, 3, 1, 0, 2, 0, 0, 1,
       4, 4, 4, 1, 1, 3, 0, 1, 3, 1, 4, 4, 2, 3, 4, 1, 4, 4, 2, 0, 2, 4,
       0, 1, 1, 4, 4, 1, 4, 0, 0, 4, 2, 2, 2, 1, 3, 3, 1, 1, 3, 3, 0, 0,
       4, 4, 3, 4, 3, 3, 0, 0, 1, 2, 4, 0, 0, 2, 4, 1, 1, 4, 4, 3, 0, 2,
       1, 0, 4, 3, 2, 1, 2, 0, 2, 2, 4, 0, 4, 2, 0, 2, 0, 3, 0, 2, 2, 0,
       3, 1, 3, 4, 0, 2, 4, 4, 1, 4, 2, 2, 3, 1, 1, 3, 1, 0, 2, 3, 4, 4,
       4, 0, 3, 2, 0, 4, 3, 3, 2, 3, 1, 2, 3, 3, 4, 0, 2, 2, 2, 1, 0, 3,
       4, 3, 3, 1, 1, 2, 0, 2, 2, 0, 2, 0, 3, 3, 4, 1, 1, 1, 1, 1, 4, 4,
       2, 3])

In [19]:
grafico = px.scatter(x=X_random[:,0], y=X_random[:,1])
grafico.show()

In [20]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

KMeans(n_clusters=5)

In [21]:
r1 = kmeans_blobs.predict(X_random)
r1

array([0, 3, 0, 3, 0, 0, 2, 2, 0, 0, 0, 0, 4, 2, 2, 0, 2, 3, 3, 0, 3, 2,
       0, 3, 1, 0, 3, 3, 1, 3, 0, 2, 2, 2, 2, 0, 1, 3, 0, 0, 2, 0, 0, 0,
       4, 1, 1, 0, 0, 3, 2, 0, 3, 0, 1, 4, 2, 3, 1, 0, 4, 4, 2, 0, 2, 1,
       0, 0, 0, 1, 1, 0, 1, 2, 3, 1, 0, 2, 2, 0, 3, 2, 0, 0, 3, 3, 2, 0,
       4, 4, 3, 4, 3, 3, 2, 0, 0, 2, 4, 0, 2, 2, 4, 0, 0, 1, 4, 3, 2, 2,
       0, 0, 4, 3, 2, 0, 2, 0, 2, 2, 4, 0, 1, 2, 0, 2, 0, 3, 0, 2, 2, 0,
       3, 0, 3, 1, 0, 2, 1, 1, 0, 1, 2, 2, 3, 0, 0, 3, 0, 0, 2, 3, 4, 4,
       1, 2, 3, 2, 0, 1, 3, 3, 2, 3, 0, 2, 3, 3, 1, 0, 2, 2, 0, 0, 0, 3,
       4, 3, 3, 0, 0, 2, 0, 2, 2, 0, 2, 2, 3, 3, 4, 0, 0, 0, 0, 0, 1, 1,
       2, 3], dtype=int32)

In [22]:
c1 = kmeans_blobs.cluster_centers_
c1

array([[ 1.72828479,  2.45681804],
       [ 9.80180753, -2.31848891],
       [-1.34380205,  3.16891232],
       [-1.48385442,  7.97740229],
       [ 8.26330644, -3.02010795]])

In [23]:
grafico1 = px.scatter(x=X_random[:,0], y=X_random[:,1], color=r1)
grafico2 = px.scatter(x=c1[:,0], y=c1[:,1], size=[12, 12, 12,12,12])
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3.show()

# Base Cartão de Crédito

## Atributos limitados


In [24]:
base_cartao = pd.read_csv('credit_card_clients.csv', header=1)
base_cartao

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [25]:
base_cartao['BILL_TOT'] = base_cartao['BILL_AMT1'] + base_cartao['BILL_AMT2'] + base_cartao['BILL_AMT3'] + base_cartao['BILL_AMT4'] + base_cartao['BILL_AMT5']

In [26]:
base_cartao

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0         -1  ...          0          0         0       689         0   
1          0  ...       3455       3261         0      1000      1000   
2          0  ...      14948      15549      1518      1500      1000   
3          0  ...      28959      29547      2000      2019      1200   
4          0  ...      19146      19131      2000     36681     10000   
...      ...  ...        ...        ...       ...       ...       ...   
29995      0  ...      31237      15980      8500     20000      5003   
29996     -1  ...       5190          0      1837      3526      8998   
29997     -1  ...      20582      19357         0         0     22000   
29998      0  ...      11855      48944     85900      3409      1178   
29999      0  ...      32428      15313      2078      1800      1430   

       PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  BILL_TOT  
0             0         0         0                           1      7704  
1          1000         0      2000                           1     13816  
2          1000      1000      5000                           0     86104  
3          1100      1069      1000                           0    201787  
4          9000       689       679                           0     90208  
...         ...       ...       ...                         ...       ...  
29995      3047      5000      1000                           0    709369  
29996       129         0         0                           0     21182  
29997      4200      2000      3100                           1     51139  
29998      1926     52964      1804                           1    217667  
29999      1000      1000      1000                           1    215561  

[30000 rows x 26 columns]

In [27]:
X_cartao = base_cartao.iloc[:,[1,25]].values
X_cartao

array([[ 20000,   7704],
       [120000,  13816],
       [ 90000,  86104],
       ...,
       [ 30000,  51139],
       [ 80000, 217667],
       [ 50000, 215561]])

In [28]:
scaler_cartao = StandardScaler()
X_cartao = scaler_cartao.fit_transform(X_cartao)
X_cartao

array([[-1.13672015, -0.68703183],
       [-0.3659805 , -0.66822573],
       [-0.59720239, -0.44580167],
       ...,
       [-1.05964618, -0.55338602],
       [-0.67427636, -0.04099347],
       [-0.90549825, -0.04747345]])

In [29]:
wcss = []
for i in range(1,11):
  kmeans_cartao = KMeans(n_clusters=i, random_state=0)
  kmeans_cartao.fit(X_cartao)
  wcss.append(kmeans_cartao.inertia_)

In [30]:
wcss

[60000.000000000146,
 35253.80349079464,
 20099.57681896242,
 15841.544624204644,
 10678.533523152999,
 8559.38399173417,
 7359.984983373501,
 6588.539894076816,
 5654.053228974774,
 5018.738560406848]

In [31]:
grafico = px.line(x=range(1,11), y=wcss)
grafico.show()

In [32]:
kmeans_cartao = KMeans(n_clusters=4, random_state=0)
kmeans_cartao.fit(X_cartao)

KMeans(n_clusters=4, random_state=0)

In [33]:
rotulos = kmeans_cartao.fit_predict(X_cartao)
rotulos

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [34]:
grafico1 = px.scatter(x=X_cartao[:,0], y=X_cartao[:,1], color=rotulos)
grafico1

In [35]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [     2, 120000,      2, ...,      1,  13816,      0],
       [     3,  90000,      2, ...,      0,  86104,      0],
       ...,
       [ 29998,  30000,      1, ...,      1,  51139,      0],
       [ 29999,  80000,      1, ...,      1, 217667,      0],
       [ 30000,  50000,      1, ...,      1, 215561,      0]])

In [36]:
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes

array([[ 11795,  10000,      1, ...,      1,  42004,      0],
       [ 11815,  30000,      2, ...,      0,  46806,      0],
       [ 11817,  50000,      1, ...,      0, 247559,      0],
       ...,
       [ 18400, 290000,      2, ...,      0, 654010,      3],
       [    18, 320000,      1, ...,      0, 770415,      3],
       [ 29996, 220000,      1, ...,      0, 709369,      3]])

## Trabalhando com mais atributos

In [48]:
X_cartao_mais = base_cartao.iloc[:,[1,2,3,4,5,25]].values
X_cartao_mais

array([[ 20000,      2,      2,      1,     24,   7704],
       [120000,      2,      2,      2,     26,  13816],
       [ 90000,      2,      2,      2,     34,  86104],
       ...,
       [ 30000,      1,      2,      2,     37,  51139],
       [ 80000,      1,      3,      1,     41, 217667],
       [ 50000,      1,      2,      1,     46, 215561]])

In [49]:
base_cartao.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', 'BILL_TOT'],
      dtype='object')

In [50]:
X_cartao_mais.shape

(30000, 6)

In [51]:
scaler_cartao_mais = StandardScaler()
X_cartao_mais = scaler_cartao_mais.fit_transform(X_cartao_mais)
X_cartao_mais

array([[-1.13672015,  0.81016074,  0.18582826, -1.05729503, -1.24601985,
        -0.68703183],
       [-0.3659805 ,  0.81016074,  0.18582826,  0.85855728, -1.02904717,
        -0.66822573],
       [-0.59720239,  0.81016074,  0.18582826,  0.85855728, -0.16115646,
        -0.44580167],
       ...,
       [-1.05964618, -1.23432296,  0.18582826,  0.85855728,  0.16430256,
        -0.55338602],
       [-0.67427636, -1.23432296,  1.45111372, -1.05729503,  0.59824792,
        -0.04099347],
       [-0.90549825, -1.23432296,  0.18582826, -1.05729503,  1.14067961,
        -0.04747345]])

In [52]:
wcss = []
for i in range(1,11):
  kmeans_cartao_mais = KMeans(n_clusters=i, random_state=0)
  kmeans_cartao_mais.fit(X_cartao)
  wcss.append(kmeans_cartao_mais.inertia_)

In [53]:
grafico = px.line(x=range(1,11), y=wcss)
grafico.show()

In [70]:
kmeans_cartao_mais = KMeans(n_clusters=4, random_state=0)
rotulos = kmeans_cartao_mais.fit_predict(X_cartao_mais)
rotulos

array([0, 1, 1, ..., 1, 3, 3], dtype=int32)

In [71]:
from sklearn.decomposition import PCA

In [72]:
pca = PCA(n_components=2)
X_cartao_mais_pca = pca.fit_transform(X_cartao_mais)

In [73]:
X_cartao_mais_pca.shape

(30000, 2)

In [74]:
X_cartao_mais_pca

array([[-0.73662246, -1.13943041],
       [-1.480228  , -0.30825621],
       [-0.94662614, -0.49268192],
       ...,
       [-0.79816121, -0.91478544],
       [ 1.17364529, -1.55915051],
       [ 1.15591676, -1.10789085]])

In [75]:
grafico1 = px.scatter(x=X_cartao_mais_pca[:,0], y=X_cartao_mais_pca[:,1], color=rotulos)
grafico1.show()

In [76]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes

array([[    29,  50000,      2, ...,      0,  39951,      0],
       [    24, 450000,      2, ...,      1,  26965,      0],
       [    22, 120000,      2, ...,      1,   1580,      0],
       ...,
       [ 29970, 200000,      1, ...,      0, 366384,      3],
       [ 29999,  80000,      1, ...,      1, 217667,      3],
       [ 30000,  50000,      1, ...,      1, 215561,      3]])