<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/Kmeans%20-%20Random%20Blobs%20-%20Machine_Learning_e_Data_Science_com_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-means - Agrupamento

In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 68.0 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [7]:
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [8]:
x = [20, 27, 21, 37, 46, 53,55,47,52,32,39,41,39,48,48]
y = [1000, 1200, 2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

In [9]:
grafico =px.scatter(x=x, y=y, title='Agrupamento de Clientes')
grafico.show()

In [11]:
matriz = []
for i in range(len(x)):
  matriz.append([x[i], y[i]])
matriz

[[20, 1000],
 [27, 1200],
 [21, 2900],
 [37, 1850],
 [46, 900],
 [53, 950],
 [55, 2000],
 [47, 2100],
 [52, 3000],
 [32, 5900],
 [39, 4100],
 [41, 5100],
 [39, 7000],
 [48, 5000],
 [48, 6500]]

In [13]:
base_salario = np.array([[20,1000], [27, 1200], [21, 2900], [37, 1850], [46, 900], [53, 950], [55, 2000], [47, 2100], [52, 3000], [32, 5900], [39, 4100], [41, 5100], [39, 7000], [48, 5000], [48, 6500]])
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [14]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [15]:
matriz = scaler_salario.fit_transform(matriz)
matriz

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [16]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [17]:
c = kmeans_salario.cluster_centers_
c

array([[-1.63312883, -0.77505093],
       [ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572]])

In [18]:
scaler_salario.inverse_transform(c)

array([[  22.66666667, 1700.        ],
       [  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ]])

In [19]:
r = kmeans_salario.labels_

In [20]:
r

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int32)

In [24]:
grafico1 = px.scatter(x=base_salario[:,0], y=base_salario[:,1], color=r)
grafico2 = px.scatter(x=c[:,0], y=c[:,1], size=[12, 12, 12])
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3.show()

# Dados Randômicos

In [36]:
from sklearn.datasets import make_blobs

In [37]:
X_random, y_random = make_blobs(n_samples=200, centers=5, random_state=0)

In [38]:
X_random

array([[ 1.36069966,  0.74802912],
       [-3.27894024,  9.89995288],
       [ 0.58894326,  4.00148458],
       [-0.97373942,  6.94454493],
       [ 2.43169305, -0.20173713],
       [ 0.62835793,  4.4601363 ],
       [-2.16434104,  2.52061045],
       [-0.65392827,  4.76656958],
       [ 0.73240494,  2.87562511],
       [ 1.956815  ,  0.23418537],
       [ 2.11567076,  3.06896151],
       [ 3.18190344, -0.18226785],
       [ 7.01769098, -3.35367647],
       [-2.34026827,  1.45145793],
       [ 0.30380963,  3.94423417],
       [ 0.829832  ,  1.74202664],
       [-3.06770103,  2.98114426],
       [-1.36641982,  7.15528181],
       [-1.10630261,  7.5161316 ],
       [ 2.41163392,  1.60423683],
       [-2.37508158,  7.10478226],
       [-2.47135027,  2.50783257],
       [ 2.47034915,  4.09862906],
       [-1.63313558,  7.9298116 ],
       [ 8.58924431, -0.67161883],
       [ 3.92282648,  1.80370832],
       [-1.38420548,  8.97235138],
       [ 1.05566092,  6.77544419],
       [ 9.08260172,

In [39]:
y_random

array([1, 3, 0, 3, 1, 0, 2, 0, 2, 1, 0, 1, 4, 2, 0, 1, 2, 3, 3, 1, 3, 2,
       0, 3, 4, 1, 3, 3, 4, 3, 1, 2, 0, 0, 2, 0, 4, 3, 1, 0, 2, 0, 0, 1,
       4, 4, 4, 1, 1, 3, 0, 1, 3, 1, 4, 4, 2, 3, 4, 1, 4, 4, 2, 0, 2, 4,
       0, 1, 1, 4, 4, 1, 4, 0, 0, 4, 2, 2, 2, 1, 3, 3, 1, 1, 3, 3, 0, 0,
       4, 4, 3, 4, 3, 3, 0, 0, 1, 2, 4, 0, 0, 2, 4, 1, 1, 4, 4, 3, 0, 2,
       1, 0, 4, 3, 2, 1, 2, 0, 2, 2, 4, 0, 4, 2, 0, 2, 0, 3, 0, 2, 2, 0,
       3, 1, 3, 4, 0, 2, 4, 4, 1, 4, 2, 2, 3, 1, 1, 3, 1, 0, 2, 3, 4, 4,
       4, 0, 3, 2, 0, 4, 3, 3, 2, 3, 1, 2, 3, 3, 4, 0, 2, 2, 2, 1, 0, 3,
       4, 3, 3, 1, 1, 2, 0, 2, 2, 0, 2, 0, 3, 3, 4, 1, 1, 1, 1, 1, 4, 4,
       2, 3])

In [40]:
grafico = px.scatter(x=X_random[:,0], y=X_random[:,1])
grafico.show()

In [41]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

KMeans(n_clusters=5)

In [42]:
r1 = kmeans_blobs.predict(X_random)
r1

array([4, 2, 0, 2, 4, 0, 3, 0, 0, 4, 4, 4, 1, 3, 0, 4, 3, 2, 2, 4, 2, 3,
       0, 2, 1, 4, 2, 0, 1, 2, 4, 3, 0, 0, 3, 0, 1, 2, 4, 0, 3, 0, 0, 4,
       1, 1, 1, 4, 4, 2, 0, 4, 2, 4, 1, 1, 3, 2, 1, 4, 1, 1, 3, 0, 3, 1,
       0, 4, 4, 1, 1, 4, 1, 0, 2, 1, 0, 3, 3, 0, 2, 0, 4, 4, 2, 2, 0, 0,
       1, 1, 2, 1, 2, 2, 0, 0, 4, 3, 1, 0, 0, 3, 1, 4, 4, 1, 1, 2, 0, 3,
       4, 0, 1, 2, 3, 4, 3, 3, 3, 3, 1, 0, 1, 0, 0, 3, 0, 2, 4, 3, 3, 0,
       2, 4, 2, 1, 0, 3, 1, 1, 4, 1, 3, 3, 2, 4, 4, 2, 4, 0, 3, 2, 1, 1,
       1, 3, 2, 3, 4, 1, 2, 2, 3, 2, 4, 3, 2, 2, 1, 0, 0, 3, 4, 4, 0, 2,
       1, 2, 2, 4, 4, 3, 0, 3, 3, 0, 3, 0, 2, 2, 1, 0, 4, 4, 4, 4, 1, 1,
       3, 2], dtype=int32)

In [43]:
c1 = kmeans_blobs.cluster_centers_
c1

array([[ 0.77140909,  4.29148991],
       [ 9.14794457, -2.61667701],
       [-1.5489702 ,  8.00822173],
       [-1.74129382,  2.70521448],
       [ 2.06843293,  1.35387645]])

In [45]:
grafico1 = px.scatter(x=X_random[:,0], y=X_random[:,1], color=r1)
grafico2 = px.scatter(x=c1[:,0], y=c1[:,1], size=[12, 12, 12,12,12])
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3.show()