<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/Machine_Learning_e_Data_Science_com_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## K-means - Agrupamento

In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 68.0 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [7]:
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [8]:
x = [20, 27, 21, 37, 46, 53,55,47,52,32,39,41,39,48,48]
y = [1000, 1200, 2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

In [9]:
grafico =px.scatter(x=x, y=y, title='Agrupamento de Clientes')
grafico.show()

In [11]:
matriz = []
for i in range(len(x)):
  matriz.append([x[i], y[i]])
matriz

[[20, 1000],
 [27, 1200],
 [21, 2900],
 [37, 1850],
 [46, 900],
 [53, 950],
 [55, 2000],
 [47, 2100],
 [52, 3000],
 [32, 5900],
 [39, 4100],
 [41, 5100],
 [39, 7000],
 [48, 5000],
 [48, 6500]]

In [13]:
base_salario = np.array([[20,1000], [27, 1200], [21, 2900], [37, 1850], [46, 900], [53, 950], [55, 2000], [47, 2100], [52, 3000], [32, 5900], [39, 4100], [41, 5100], [39, 7000], [48, 5000], [48, 6500]])
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [14]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [15]:
matriz = scaler_salario.fit_transform(matriz)
matriz

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [16]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [17]:
c = kmeans_salario.cluster_centers_
c

array([[-1.63312883, -0.77505093],
       [ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572]])

In [18]:
scaler_salario.inverse_transform(c)

array([[  22.66666667, 1700.        ],
       [  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ]])

In [19]:
r = kmeans_salario.labels_

In [20]:
r

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int32)

In [24]:
grafico1 = px.scatter(x=base_salario[:,0], y=base_salario[:,1], color=r)
grafico2 = px.scatter(x=c[:,0], y=c[:,1], size=[12, 12, 12])
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3.show()