<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/ML_e_DS_com_Python_Regress%C3%A3o_Polinomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Regressão polinomial

## Base plano de saude 2

In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 84.6 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [2]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from yellowbrick.regressor import ResidualsPlot

In [3]:
base_plano_saude2 = pd.read_csv('plano_saude2.csv')

In [4]:
X_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values

In [5]:
X_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [6]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [13]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly = PolynomialFeatures(degree = 4)
X_poly = poly.fit_transform(X_plano_saude2)

In [14]:
X_poly.shape

(10, 5)

In [15]:
X_poly[0]

array([1.00000e+00, 1.80000e+01, 3.24000e+02, 5.83200e+03, 1.04976e+05])

In [16]:
regressor_poly = LinearRegression()
regressor_poly.fit(X_poly, y_plano_saude2)

LinearRegression()

In [17]:
regressor_poly.intercept_

16561.97463791193

In [18]:
regressor_poly.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [19]:
novo_registro = [[40]]

In [20]:
regressor_poly.predict(poly.transform(novo_registro))

array([1335.33958015])

In [21]:
previsoes = regressor_poly.predict(X_poly)
previsoes

array([ 549.65035464,  345.85081575,  616.53845992,  975.8391595 ,
       1249.06759853, 1472.7272727 , 1894.51048941, 2973.2983677 ,
       5379.16083828, 9993.35664357])

In [23]:
grafico = px.scatter(x = X_plano_saude2[:,0], y = y_plano_saude2)
grafico.add_scatter(x = X_plano_saude2[:,0], y = previsoes, name = 'Regressão polinomial')
grafico.show()

In [24]:
regressor_poly.score(X_poly, y_plano_saude2)

0.9976494147321991

## Base preço das casas

In [25]:
base_pcasas = pd.read_csv('house_prices.csv')

In [26]:
X_casas = base_pcasas.iloc[:, 3:19].values
y_casas = base_pcasas.iloc[:, 2].values

In [30]:

from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste,y_casas_treinamentro, y_casas_teste = train_test_split(X_casas, y_casas, test_size = 0.3, random_state = 0)

In [31]:
X_casas_treinamento.shape

(15129, 16)

In [33]:
X_casas_teste.shape

(6484, 16)

In [34]:
poly = PolynomialFeatures(degree = 2)
X_casas_treinamento_poly = poly.fit_transform(X_casas_treinamento)
X_casas_teste_poly = poly.transform(X_casas_teste)

In [35]:
X_casas_treinamento_poly.shape,X_casas_teste_poly.shape

((15129, 153), (6484, 153))

In [36]:
regressor_poly = LinearRegression()
regressor_poly.fit(X_casas_treinamento_poly, y_casas_treinamentro)

LinearRegression()

In [37]:
regressor_poly.score(X_casas_treinamento_poly, y_casas_treinamentro)

0.7924863532416322

In [38]:
regressor_poly.score(X_casas_teste_poly, y_casas_teste)

0.7945486448881894

In [40]:
previsoes = regressor_poly.predict(X_casas_teste_poly)
previsoes

array([ 442197.02085688, 1956399.29323969,  576589.98087715, ...,
        350582.46928258,  246776.53597106,  221178.81139611])

In [41]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [42]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste, previsoes)

105307.16389416289