<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/Redes_Neurais_Artificiais_Machine_Learning_e_Data_Science_com_Python_de_A_a_Z.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Redes Neurais Artificiais

## Base plano de saúde

In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 22.0 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [2]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from yellowbrick.regressor import ResidualsPlot

In [3]:
base_plano_saude2 = pd.read_csv('plano_saude2.csv')

In [4]:
X_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values

In [5]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X_plano_saude2_scaled = scaler_x.fit_transform(X_plano_saude2)
scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1, 1))

In [6]:
X_plano_saude2_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [8]:
y_plano_saude2_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [11]:
from sklearn.neural_network import MLPRegressor
regressor_rna = MLPRegressor(max_iter=1000)
regressor_rna.fit(X_plano_saude2_scaled, y_plano_saude2_scaled)

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1650: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPRegressor(max_iter=1000)

In [12]:
regressor_rna.score(X_plano_saude2_scaled, y_plano_saude2_scaled)

0.9641994162459059

In [15]:
grafico = px.scatter(x=X_plano_saude2_scaled.ravel(), y=y_plano_saude2_scaled.ravel())
grafico.add_scatter(x=X_plano_saude2_scaled.ravel(), y=regressor_rna.predict(X_plano_saude2_scaled).ravel(), mode='lines')
grafico.show()

In [16]:
novo = [[40]]
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [21]:
scaler_y.inverse_transform(regressor_rna.predict(novo).reshape(-1,1))

array([[1143.39782976]])

## Base de dados preço das casas

In [22]:

base_casas = pd.read_csv('house_prices.csv')
base_casas.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [23]:
X_casas = base_casas.iloc[:, 3:19].values
y_casas = base_casas.iloc[:, 2].values

In [24]:
from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(X_casas, y_casas, test_size=0.3, random_state=0)


In [25]:
X_casas_treinamento.shape

(15129, 16)

In [26]:
from sklearn.preprocessing import StandardScaler
scaler_x_casas = StandardScaler()
X_casas_treinamento_scaled = scaler_x_casas.fit_transform(X_casas_treinamento)

In [27]:
scaler_y_casas = StandardScaler()
y_casas_treinamento_scaled = scaler_y_casas.fit_transform(y_casas_treinamento.reshape(-1, 1))

In [28]:
X_casas_teste_scaled = scaler_x_casas.transform(X_casas_teste)
y_casas_teste_scaled = scaler_y_casas.transform(y_casas_teste.reshape(-1, 1))

In [29]:
X_casas_treinamento_scaled.shape

(15129, 16)

In [30]:
X_casas_teste_scaled.shape

(6484, 16)

In [31]:
y_casas_teste_scaled.shape

(6484, 1)

In [32]:
y_casas_treinamento_scaled

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [34]:
regressor_rna_casas = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9, 9))
regressor_rna_casas.fit(X_casas_treinamento_scaled, y_casas_treinamento_scaled)

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1650: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [36]:
regressor_rna_casas.score(X_casas_treinamento_scaled, y_casas_treinamento_scaled)

0.8757349760019294

In [37]:
regressor_rna_casas.score(X_casas_teste_scaled, y_casas_teste_scaled)

0.8703418287207076

In [38]:
previsoes = regressor_rna_casas.predict(X_casas_teste_scaled)

In [39]:
previsoes

array([-0.48326949,  4.56501774,  0.13811409, ..., -0.36490925,
       -0.86271535, -0.9222435 ])

In [40]:
y_casas_teste_scaled

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [43]:
y_casas_teste_inverse = scaler_y_casas.inverse_transform(y_casas_teste_scaled)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes.reshape(-1, 1))

In [44]:
previsoes_inverse

array([[ 363901.14576885],
       [2209787.32169937],
       [ 591107.58279423],
       ...,
       [ 407179.09656566],
       [ 225158.27595191],
       [ 203392.04363408]])

In [45]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_casas_teste, previsoes_inverse)
mae

78496.89019789353