<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/Sele%C3%A7%C3%A3o_de_atributos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Seleção de atributos

## Preparando a base de dados

In [1]:
import pandas as pd
base_census = pd.read_csv('/content/census.csv')
base_census.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [3]:
colunas = base_census.columns[:-1]
colunas

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country'],
      dtype='object')

In [4]:
X_census = base_census.iloc[:, 0:14].values
y_census = base_census.iloc[:, 14].values

In [5]:
X_census

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [6]:
y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:,1])
X_census[:,3] = label_encoder_education.fit_transform(X_census[:,3])
X_census[:,5] = label_encoder_marital.fit_transform(X_census[:,5])
X_census[:,6] = label_encoder_occupation.fit_transform(X_census[:,6])
X_census[:,7] = label_encoder_relationship.fit_transform(X_census[:,7])
X_census[:,8] = label_encoder_race.fit_transform(X_census[:,8])
X_census[:,9] = label_encoder_sex.fit_transform(X_census[:,9])
X_census[:,13] = label_encoder_country.fit_transform(X_census[:,13])

In [9]:
X_census

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler_census = MinMaxScaler()
X_census = scaler_census.fit_transform(X_census)

In [12]:
X_census.shape

(32561, 14)

## Low variance

In [13]:
for i in range(X_census.shape[1]):
  print(i, X_census[:,i].var())
#

0 0.034913808595952486
1 0.03312115190663569
2 0.005138537590667898
3 0.06657103564450892
4 0.029416385024073417
5 0.06301761677301636
6 0.09123816653931152
7 0.10326534394406342
8 0.04502805169292987
9 0.22136950173699113
10 0.00545419549240862
11 0.008557270623428908
12 0.015874043397822807
13 0.03641266114220053


In [15]:
from sklearn.feature_selection import VarianceThreshold
selecao = VarianceThreshold(threshold=0.05)
X_census_variancia = selecao.fit_transform(X_census)
X_census_variancia.shape

(32561, 5)

In [16]:
X_census_variancia

array([[0.6       , 0.66666667, 0.07142857, 0.2       , 1.        ],
       [0.6       , 0.33333333, 0.28571429, 0.        , 1.        ],
       [0.73333333, 0.        , 0.42857143, 0.2       , 1.        ],
       ...,
       [0.73333333, 1.        , 0.07142857, 0.8       , 0.        ],
       [0.73333333, 0.66666667, 0.07142857, 0.6       , 1.        ],
       [0.73333333, 0.33333333, 0.28571429, 1.        , 0.        ]])

In [17]:
selecao.variances_

array([0.03491381, 0.03312115, 0.00513854, 0.06657104, 0.02941639,
       0.06301762, 0.09123817, 0.10326534, 0.04502805, 0.2213695 ,
       0.0054542 , 0.00855727, 0.01587404, 0.03641266])

In [18]:
import numpy as np
indices = np.where(selecao.variances_ > 0.05)
indices

(array([3, 5, 6, 7, 9]),)

In [19]:
colunas[indices]

Index(['education', 'marital-status', 'occupation', 'relationship', 'sex'], dtype='object')

In [21]:
base_census_variancia = base_census.drop(columns = ['age', 'workclass', 'final-weight','education-num','race', 'capital-gain','capital-loos','hour-per-week','native-country'],axis=1)

In [27]:
base_census_variancia

education       marital-status          occupation    relationship  \
0        Bachelors        Never-married        Adm-clerical   Not-in-family   
1        Bachelors   Married-civ-spouse     Exec-managerial         Husband   
2          HS-grad             Divorced   Handlers-cleaners   Not-in-family   
3             11th   Married-civ-spouse   Handlers-cleaners         Husband   
4        Bachelors   Married-civ-spouse      Prof-specialty            Wife   
...            ...                  ...                 ...             ...   
32556   Assoc-acdm   Married-civ-spouse        Tech-support            Wife   
32557      HS-grad   Married-civ-spouse   Machine-op-inspct         Husband   
32558      HS-grad              Widowed        Adm-clerical       Unmarried   
32559      HS-grad        Never-married        Adm-clerical       Own-child   
32560      HS-grad   Married-civ-spouse     Exec-managerial            Wife   

           sex  income  
0         Male   <=50K  
1         Male   <=50K  
2         Male   <=50K  
3         Male   <=50K  
4       Female   <=50K  
...        ...     ...  
32556   Female   <=50K  
32557     Male    >50K  
32558   Female   <=50K  
32559     Male   <=50K  
32560   Female    >50K  

[32561 rows x 6 columns]

In [28]:
X_census_variancia = base_census_variancia.iloc[:,0:5].values
y_census_variancia = base_census_variancia.iloc[:,5].values

In [29]:
X_census_variancia

array([[' Bachelors', ' Never-married', ' Adm-clerical',
        ' Not-in-family', ' Male'],
       [' Bachelors', ' Married-civ-spouse', ' Exec-managerial',
        ' Husband', ' Male'],
       [' HS-grad', ' Divorced', ' Handlers-cleaners', ' Not-in-family',
        ' Male'],
       ...,
       [' HS-grad', ' Widowed', ' Adm-clerical', ' Unmarried', ' Female'],
       [' HS-grad', ' Never-married', ' Adm-clerical', ' Own-child',
        ' Male'],
       [' HS-grad', ' Married-civ-spouse', ' Exec-managerial', ' Wife',
        ' Female']], dtype=object)

In [30]:
y_census_variancia

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [32]:
X_census_variancia[:,0] = label_encoder_education.fit_transform(X_census_variancia[:,0])
X_census_variancia[:,1] = label_encoder_marital.fit_transform(X_census_variancia[:,1])
X_census_variancia[:,2] = label_encoder_occupation.fit_transform(X_census_variancia[:,2])
X_census_variancia[:,3] = label_encoder_relationship.fit_transform(X_census_variancia[:,3])
X_census_variancia[:,4] = label_encoder_sex.fit_transform(X_census_variancia[:,4])

In [33]:
X_census_variancia

array([[9, 4, 1, 1, 1],
       [9, 2, 4, 0, 1],
       [11, 0, 6, 1, 1],
       ...,
       [11, 6, 1, 4, 0],
       [11, 4, 1, 3, 1],
       [11, 2, 4, 5, 0]], dtype=object)

In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
onehotencorder = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0,1,2,3,4])],remainder='passthrough')
X_census_variancia = onehotencorder.fit_transform(X_census_variancia).toarray()
X_census_variancia

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [35]:
scaler = MinMaxScaler()
X_census_variancia = scaler.fit_transform(X_census_variancia)
X_census_variancia

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [36]:
from sklearn.model_selection import train_test_split
X_census_treinamento_var,X_census_teste_var, y_census_treinamento_var,y_census_teste_var = train_test_split(X_census_variancia,y_census_variancia,test_size=0.15, random_state = 0)

In [37]:
X_census_treinamento_var.shape, X_census_teste_var.shape

((27676, 46), (4885, 46))

In [40]:
from sklearn.ensemble import RandomForestClassifier
random_forest_var = RandomForestClassifier(criterion='entropy',min_samples_leaf=1, min_samples_split=5, n_estimators=100)
random_forest_var.fit(X_census_treinamento_var, y_census_treinamento_var)

RandomForestClassifier(criterion='entropy', min_samples_split=5)

In [41]:
from sklearn.metrics import accuracy_score, classification_report
previsoes_var = random_forest_var.predict(X_census_teste_var)
accuracy_score(y_census_teste_var, previsoes_var)

0.816171954964176

## Extra Tree

In [58]:
from sklearn.ensemble import ExtraTreesClassifier

In [59]:
selecao = ExtraTreesClassifier()
selecao.fit(X_census,y_census)

ExtraTreesClassifier()

In [60]:
importancias = selecao.feature_importances_

In [61]:
importancias

array([0.1514393 , 0.04662697, 0.1596281 , 0.0348226 , 0.0909547 ,
       0.07661415, 0.07733028, 0.09136332, 0.01468769, 0.02774301,
       0.08856591, 0.02794653, 0.09429642, 0.01798101])

In [62]:
colunas

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country'],
      dtype='object')

In [63]:
indices = []
for i in range(len(importancias)):
  if importancias[i] >= 0.029:
    indices.append(i)

In [64]:
indices

[0, 1, 2, 3, 4, 5, 6, 7, 10, 12]

In [65]:
colunas[indices]

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'capital-gain',
       'hour-per-week'],
      dtype='object')

In [66]:
X_census = base_census.iloc[:, 0:14].values
y_census = base_census.iloc[:, 14].values

In [71]:
X_census_extra = X_census[:,indices]
X_census_extra

array([[39, ' State-gov', 77516, ..., ' Not-in-family', 2174, 40],
       [50, ' Self-emp-not-inc', 83311, ..., ' Husband', 0, 13],
       [38, ' Private', 215646, ..., ' Not-in-family', 0, 40],
       ...,
       [58, ' Private', 151910, ..., ' Unmarried', 0, 40],
       [22, ' Private', 201490, ..., ' Own-child', 0, 20],
       [52, ' Self-emp-inc', 287927, ..., ' Wife', 15024, 40]],
      dtype=object)

In [72]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
onehotencorder = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,3,5,6,7])],remainder='passthrough')
X_census_extra = onehotencorder.fit_transform(X_census_extra).toarray()
X_census_extra

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.3000e+01, 2.1740e+03,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.3000e+01, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 1.5024e+04,
        4.0000e+01]])

In [73]:
X_census_extra.shape

(32561, 58)

In [75]:
from sklearn.model_selection import train_test_split
X_census_treinamento_extra,X_census_teste_extra, y_census_treinamento_extra,y_census_teste_extra = train_test_split(X_census_extra,y_census,test_size=0.15, random_state = 0)

In [76]:
X_census_treinamento_extra.shape, X_census_teste_extra.shape

((27676, 58), (4885, 58))

In [77]:
from sklearn.ensemble import RandomForestClassifier
random_forest_extra = RandomForestClassifier(criterion='entropy',min_samples_leaf=1, min_samples_split=5, n_estimators=100)
random_forest_extra.fit(X_census_treinamento_extra, y_census_treinamento_extra)

RandomForestClassifier(criterion='entropy', min_samples_split=5)

In [78]:
from sklearn.metrics import accuracy_score, classification_report
previsoes_extra = random_forest_extra.predict(X_census_teste_extra)
accuracy_score(y_census_teste_extra, previsoes_extra)

0.8474923234390993