<a href="https://colab.research.google.com/github/LKSfiuza/Machine-Learning-projects/blob/main/%C3%81rvores_de_decis%C3%A3o_e_Random_Forest_Machine_Learning_e_Data_Science_com_Python_de_A_a_Z_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Árvores de decisão

## Base Plano de Saúde

In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 39.0 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [2]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from yellowbrick.regressor import ResidualsPlot

In [5]:
base_plano_saude2 = pd.read_csv('plano_saude2.csv')
base_plano_saude2.head()

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150

In [6]:
X_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values

In [7]:
X_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [8]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [9]:
from sklearn.tree import DecisionTreeRegressor
regressor_arvore_saude = DecisionTreeRegressor()
regressor_arvore_saude.fit(X_plano_saude2, y_plano_saude2)

DecisionTreeRegressor()

In [10]:
previsoes = regressor_arvore_saude.predict(X_plano_saude2)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [11]:
regressor_arvore_saude.score(X_plano_saude2, y_plano_saude2)

1.0

In [12]:
grafico = px.scatter(x = X_plano_saude2.ravel(), y = y_plano_saude2)
grafico.add_scatter(x = X_plano_saude2.ravel(), y = previsoes, name = 'Regressão')
grafico.show()

In [14]:
X_teste_arvore = np.arange(min(X_plano_saude2), max(X_plano_saude2), 0.1)
X_teste_arvore

<ipython-input-14-09c963292261>:1: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [16]:
X_teste_arvore = X_teste_arvore.reshape(-1, 1)
X_teste_arvore.shape

(450, 1)

In [18]:
grafico = px.scatter(x = X_plano_saude2.ravel(), y = y_plano_saude2)
grafico.add_scatter(x = X_teste_arvore.ravel(), y = regressor_arvore_saude.predict(X_teste_arvore), name = 'Regressão')
grafico.show()

In [19]:
regressor_arvore_saude.predict([[40]])

array([1150.])

In [20]:
regressor_arvore_saude.predict([[40.6]])

array([1530.])

##Base preço das casas

In [21]:
base_pcasas = pd.read_csv('house_prices.csv')
base_pcasas.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [22]:
X_casas = base_pcasas.iloc[:, 3:19].values
y_casas = base_pcasas.iloc[:, 2].values

In [23]:
from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste,y_casas_treinamentro, y_casas_teste = train_test_split(X_casas, y_casas, test_size = 0.3, random_state = 0)

In [25]:
X_casas_treinamento.shape

(15129, 16)

In [27]:
y_casas_treinamentro

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [28]:
X_casas_teste.shape

(6484, 16)

In [29]:
regressor_arvore_casas = DecisionTreeRegressor()
regressor_arvore_casas.fit(X_casas_treinamento, y_casas_treinamentro)

DecisionTreeRegressor()

In [30]:
regressor_arvore_casas.score(X_casas_treinamento, y_casas_treinamentro)

0.9992712177726063

In [31]:
regressor_arvore_casas.score(X_casas_teste, y_casas_teste)

0.7171756842447476

In [32]:
previsoes_casas = regressor_arvore_casas.predict(X_casas_teste)
previsoes_casas

array([ 288000., 1835000.,  480000., ...,  289000.,  215000.,  205000.])

In [33]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [34]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste, previsoes_casas)

100053.12199259717

# Random Forest

## Base de dados plano de saúde

In [36]:
X_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [37]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [38]:
from sklearn.ensemble import RandomForestRegressor
regressor_random_saude = RandomForestRegressor(n_estimators = 10)
regressor_random_saude.fit(X_plano_saude2, y_plano_saude2)

RandomForestRegressor(n_estimators=10)

In [39]:
regressor_random_saude.score(X_plano_saude2, y_plano_saude2)

0.987091434258704

In [42]:
grafico = px.scatter(x = X_plano_saude2.ravel(), y = y_plano_saude2)
grafico.add_scatter(x = X_teste_arvore.ravel(), y = regressor_random_saude.predict(X_teste_arvore), name = 'RF')
grafico.show()

In [43]:
regressor_random_saude.predict([[40]])

array([1150.])

In [44]:
regressor_random_saude.predict([[40.6]])

array([1340.])

## Base preço das casas

In [45]:
X_casas_treinamento.shape

(15129, 16)

In [46]:
X_casas_treinamento

array([[ 4.00000e+00,  1.50000e+00,  1.39000e+03, ...,  9.81330e+04,
         4.77224e+01, -1.22332e+02],
       [ 3.00000e+00,  1.50000e+00,  1.45000e+03, ...,  9.81330e+04,
         4.77725e+01, -1.22349e+02],
       [ 5.00000e+00,  2.75000e+00,  2.86000e+03, ...,  9.80520e+04,
         4.77082e+01, -1.22104e+02],
       ...,
       [ 3.00000e+00,  2.25000e+00,  2.36000e+03, ...,  9.80420e+04,
         4.73856e+01, -1.22158e+02],
       [ 4.00000e+00,  2.00000e+00,  2.37000e+03, ...,  9.80010e+04,
         4.72831e+01, -1.22279e+02],
       [ 4.00000e+00,  2.25000e+00,  2.38000e+03, ...,  9.80080e+04,
         4.76126e+01, -1.22120e+02]])

In [49]:
y_casas_treinamentro.shape

(15129,)

In [48]:
y_casas_treinamentro

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [53]:
regressor_random_casas = RandomForestRegressor(n_estimators = 100)
regressor_random_casas.fit(X_casas_treinamento, y_casas_treinamentro)

RandomForestRegressor()

In [54]:
regressor_random_casas.score(X_casas_treinamento, y_casas_treinamentro)

0.9815427171874695

In [55]:
regressor_random_casas.score(X_casas_teste, y_casas_teste)

0.8804388305307254

In [56]:
previsoes_casas_rf = regressor_random_casas.predict(X_casas_teste)
previsoes_casas_rf

array([ 309891.5       , 1716711.86666667,  542456.02      , ...,
        372972.64      ,  228928.48      ,  201283.86      ])

In [57]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [58]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste, previsoes_casas_rf)

67683.69660618446